image: node

cache:
  paths:
    - node_modules/

stages:
  - deploy-prod

deploy-prod:
  stage: deploy-prod
  before_script:
    - apt-get update -qy
    - apt-get install -y lftp
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - echo 'Building production'
    - lftp -v
    - node -v
    - yarn build
    - echo 'Deploying to Host'
    - ls /builds/medanosol/projects/grufercan/public/
    # - lftp -v -u medanosol.es,"qY@5J4G8SwPK" sftp://medanosol.es@ssh.medanosol.es -e "set sftp:auto-confirm yes;set ssl:verify-certificate no; cd testing; mkdir testingolder;exit"
    - lftp -c "set sftp:auto-confirm yes;set ssl:verify-certificate no; open -u medanosol.es,'qY@5J4G8SwPK' sftp://medanosol.es@ssh.medanosol.es; cd testing"
  only:
    - develop

    # mirror -R --parallel=10 /builds/medanosol/projects/grufercan/public .;
