image: node:buster

cache:
  paths:
    - node_modules/

stages:
  - deploy-stage

deploy-stage:
  stage: deploy-stage
  before_script:
    - apt-get update -qy
    - apt-get install -y lftp
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - echo 'Building staging'
    - lftp -v
    - node -v
    # - yarn build
    - echo 'Deploying to Staging Host'
    # - ls /builds/medanosol/projects/grufercan/public/

    - lftp -d -e "set sftp:auto-confirm yes;set ssl:check-hostname no; set ssl:verify-certificate no;set -a; open sftp://$FTP_HOST_STAGE -u '$FTP_USER_STAGE','$FTP_PASS_STAGE'; cd testing; mirror -v -R /builds/medanosol/projects/grufercan/public/ ./ --parallel=10;bye"
    - lftp -d -e "set sftp:auto-confirm yes;set ssl:check-hostname no; set ssl:verify-certificate no;set -a; open sftp://$FTP_HOST_STAGE -u '$FTP_USER_STAGE','$FTP_PASS_STAGE'; cd testing; mirror -v -R /builds/medanosol/projects/grufercan/api/ ./api/ --parallel=10;bye"

  only:
    - staging
