image: node:buster

cache:
  paths:
    - node_modules/

stages:
  - deploy-prod

deploy-prod:
  stage: deploy-prod
  before_script:
    - apt-get update -qy
    - apt-get install -y lftp
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - echo 'Building production'
    - lftp -v
    - node -v
    - yarn build
    - echo 'Deploying to Host'
    - ls /builds/medanosol/projects/grufercan/public/

    - lftp -d -e "set sftp:auto-confirm yes;set ssl:check-hostname no; set ssl:verify-certificate no;set -a; open sftp://ssh.medanosol.es -u 'medanosol.es','qY@5J4G8SwPK'; cd testing; mirror -v -R /builds/medanosol/projects/grufercan/public/ ./ --parallel=10;bye"
    - lftp -d -e "set sftp:auto-confirm yes;set ssl:check-hostname no; set ssl:verify-certificate no;set -a; open sftp://ssh.medanosol.es -u 'medanosol.es','qY@5J4G8SwPK'; cd testing; mirror -v -R /builds/medanosol/projects/grufercan/api/ ./api/ --parallel=10;bye"

  only:
    - main
