<?php

namespace ContainerSePAHxb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoticiasEnRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\NoticiasEnRepository' shared autowired service.
     *
     * @return \App\Repository\NoticiasEnRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\NoticiasEnRepository'] = new \App\Repository\NoticiasEnRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
