<?php

namespace ContainerXVHcRTz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoticiasEsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\NoticiasEsRepository' shared autowired service.
     *
     * @return \App\Repository\NoticiasEsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\NoticiasEsRepository'] = new \App\Repository\NoticiasEsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
