<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVhtd0tT\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVhtd0tT/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVhtd0tT.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVhtd0tT\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerVhtd0tT\App_KernelProdContainer([
    'container.build_hash' => 'Vhtd0tT',
    'container.build_id' => '2c4e1348',
    'container.build_time' => 1641830179,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVhtd0tT');
