<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXVHcRTz\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXVHcRTz/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXVHcRTz.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXVHcRTz\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXVHcRTz\App_KernelProdContainer([
    'container.build_hash' => 'XVHcRTz',
    'container.build_id' => '7faeeacb',
    'container.build_time' => 1641826073,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXVHcRTz');
