<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH7swppf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH7swppf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH7swppf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH7swppf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH7swppf\App_KernelDevDebugContainer([
    'container.build_hash' => 'H7swppf',
    'container.build_id' => '9066133d',
    'container.build_time' => 1639992559,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH7swppf');
