<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTRHww6q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTRHww6q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTRHww6q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTRHww6q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTRHww6q\App_KernelDevDebugContainer([
    'container.build_hash' => 'TRHww6q',
    'container.build_id' => '84203022',
    'container.build_time' => 1641552676,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTRHww6q');
