<?php

namespace ContainerVhtd0tT;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailerControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MailerController' shared autowired service.
     *
     * @return \App\Controller\MailerController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MailerController'] = $instance = new \App\Controller\MailerController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\MailerController', $container));

        return $instance;
    }
}
